# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

  app.twig_extension:
        class: AppBundle\Twig\DevHumanExtension
        arguments: ["@=service('doctrine').getManager()"]
        public: false
        tags:
            - { name: twig.extension }

  redis:
        class: AppBundle\Service\RedisService
        arguments: [ "%predis_settings%" ]

  cache:
        class: AppBundle\Service\RedisCacheService
        arguments: ["@redis"]


  sonata.admin.collection:
      class: AppBundle\Admin\CollectionAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Content", label: "Collections" }
      arguments:
          - ~
          - AppBundle\Entity\Collection
          - ~
      calls:
          - [ setTranslationDomain, [AppBundle]]

  sonata.admin.user:
      class: AppBundle\Admin\UserAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "People", label: "Users" }
      arguments:
          - ~
          - AppBundle\Entity\User
          - ~
      calls:
          - [ setTranslationDomain, [AppBundle]]

  sonata.admin.story:
      class: AppBundle\Admin\StoryAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Content", label: "Stories" }
      arguments:
          - ~
          - AppBundle\Entity\Story
          - ~
      calls:
          - [ setTranslationDomain, [AppBundle]]